### ISSUE TITLE
Doesn't work on 32:9 Ultra-wide? 

### ISSUE THREAD

**Issue by eirhardt** [FakeMichau/TerrariaZoomPatcher#1]
Hi, do you still monitor this repo at all? I'm trying to run terraria on a Odyssey G9 super-ultrawide monitor, and it seems to crash the game when the horizontal resolution is 4000+ pixels. Any ideas?

**Comment by mataha** [comment]
I think that's a limitation of the engine; on 4096+ the game crashes.

**Comment by eirhardt** [comment]
Yeah, I believe you are correct
